### ISSUE TITLE
Update examples to only ignore requests to `127.0.0.1` in logs

### ISSUE THREAD

**Issue by diego-aquino** [zimicjs/zimic#406]
Usually when testing backend applications, we want to ignore warnings of unhandled requests to localhost, while showing other unhandled requests.

The examples https://github.com/zimicjs/zimic/tree/canary/examples/with-vitest-node and https://github.com/zimicjs/zimic/tree/canary/examples/with-jest-node currently ignore all of the unhandled requests:

https://github.com/zimicjs/zimic/blob/c699b221da5b90700853b1f62a4c5c9e6bec2c9c/examples/with-vitest-node/tests/setup.ts#L6

We could change them to only ignore requests to `127.0.0.1`, since they are the ones made by the testing framework to the application:

```ts
httpInterceptor.default.onUnhandledRequest(async (request, context) => {
  const url = new URL(request.url);

  if (url.hostname !== '127.0.0.1') {
    await context.log();
  }
});
```

**Comment by emanamoura** [comment]
@diego-aquino, could you assign me to this?
