### ISSUE TITLE
How to use zimic to intercept Supabase Auth?

### ISSUE THREAD

**Issue by irvile** [zimicjs/zimic#64]
Hi, @diego-aquino 

I'm trying to use zimic with supabase.

### scenario:
```js
const supabaseInterceptor = createHttpInterceptor<{
	'/auth/v1/admin/users': {
		POST: {
			request: {
				body: { email: 'email@mail.com'; password: '123456' }
			}
			response: {
				200: { body: { user: { id: '123' } } }
			}
		}
	}
}>({
	worker,
	baseURL: 'http://localhost:8000'
})
```

My supabase environtment:

### SUPABASE ENVS
SUPABASE_URL=http://localhost:8000

### Details:

node: 20.10.0
honojs: 4.0.0

### Error message:
ConnectionRefused: Unable to connect. Is the computer able to access the url?
 path: "http://localhost:8000/auth/v1/admin/users"

Keep going! amazing work here!

**Comment by diego-aquino** [comment]
Hi, @irvile! Thanks for the detailed description.

To confirm, did you start your `worker`? If you're using zimic in tests, you could add the following code to your test setup file:

```ts
beforeAll(async () => {
  await worker.start()
})

afterAll(async () => {
  await worker.stop()
})
```

Also, did you apply any mock responses to `/auth/v1/admin/users`? Creating the interceptor only declares the schema, so mocking endpoints is another step, using `interceptor.post` in your scenario:

```ts
const loginTracker = supabaseInterceptor
  .post('/auth/v1/admin/users')
  .respond({
    status: 200,
    body: { user: { id: '123' } },
  })

// Now, POST requests to /auth/v1/admin/users will be mocked!
```

Finally (more of a tip), the interceptor schema declares the **types** of the requests and responses the endpoint accepts. In your case, I believe the following format would be more general:

```ts
const supabaseInterceptor = createHttpInterceptor<{
  '/auth/v1/admin/users': {
    POST: {
      request: {
        body: { email: string; password: string }
      }
      response: {
        200: { body: { user: { id: string } } }
      }
    }
  }
}>({
  worker,
  baseURL: process.env.SUPABASE_URL,
})
```

**Comment by irvile** [comment]
I started the worker and tracker, but I still encountered a 'ConnectionRefused' error. Afterward, I will create a repository to reproduce this issue.

**Comment by diego-aquino** [comment]
@irvile, as part of https://github.com/diego-aquino/zimic/issues/34, I'm creating example projects with popular setups. As of now, I've created Node.js, JSDOM, and browser using Jest and Vitest. The examples are current on [my partial branch](https://github.com/diego-aquino/zimic/tree/%40diego-aquino/34-example-projects/examples), if you'd like to take a look and compare to your project. I'll let you know when they are finished.

Investigating more about connection refused errors, one possible cause is that MSW (and Zimic by consequence) only applies mocks to the current process, which makes it hard to use in multi-process projects (e.g. a frontend test trying to apply mocks to a backend reaching an external service). I started planning a new feature and API primitives on https://github.com/diego-aquino/zimic/issues/75, which I'm calling "remote HTTP interceptors". I believe they could extend Zimic to multi-process cases, if yours is one of them. Let me know if you have any ideias about it!

**Comment by diego-aquino** [comment]
Hi, @irvile!

Among other thins, [v0.4](https://github.com/zimicjs/zimic/releases/tag/v0.4.0) introduced [remote interceptors](https://github.com/zimicjs/zimic?tab=readme-ov-file#remote-http-interceptors) and [v0.5](https://github.com/zimicjs/zimic/releases/tag/v0.5.0) improved the logs about unhandled requests. Take a look at the documentation to check if remote interceptors solve the problem you're facing.

- [Basic usage](https://github.com/zimicjs/zimic?tab=readme-ov-file#basic-usage)
- [Choosing between local and remote interceptors](https://github.com/zimicjs/zimic?tab=readme-ov-file#3-choose-your-method-to-intercept-requests)
- [Creating an HTTP interceptor](https://github.com/zimicjs/zimic?tab=readme-ov-file#httpcreateinterceptor)

I'll close this issue for now. Feel free to re-open it if the problem persists!
